_base_: "default.yml"
defaults:
  - _self_

seed: 0
model_name: LPOSS

model:
  type: LPOSS
  clip_backbone: maskclip

  # DINOv2
  dino_repo: facebookresearch/dinov2
  dino_model: dinov2_vitb14
  dino_source: github
  dino_weights: null     # torch.hub сам скачает

  vit_arch: vit_base     # можно оставить, но реально не используется
  vit_patch_size: 14     # ВАЖНО: у ViT-B/14 patch_size = 14
  enc_type_feats: "v"


alpha: 0.95
gamma: 3.0
k: 400
sigma: 0.01
pix_dist_pow: 1.0
pixel_refine: true
tau: 0.01
r: 13

output: ""  # CHANGE to your results folder


evaluate:
  eval_only: true
  task:
    - voc
    - context
    - coco_object
    - context59
    - voc20
    - coco_stuff
    - cityscapes
    - ade20k

  # evaluation
  voc: segmentation/configs/_base_/datasets/pascal_voc12.py
  voc20: segmentation/configs/_base_/datasets/pascal_voc12_20.py
  context: segmentation/configs/_base_/datasets/pascal_context.py
  context59: segmentation/configs/_base_/datasets/pascal_context59.py
  coco_stuff: segmentation/configs/_base_/datasets/stuff.py
  coco_object: segmentation/configs/_base_/datasets/coco.py
  cityscapes: segmentation/configs/_base_/datasets/cityscapes.py
  ade20k: segmentation/configs/_base_/datasets/ade20k.py